apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database-monitoring
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
  MYSQL_USER: bXlzcWx1c2Vy
  MYSQL_PASSWORD: dXNlcnBhc3N3b3Jk